version: '3'
services:
  postgres:
    image: postgres:10-alpine
    container_name: forge-database
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=forge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
