swagger: '2.0'
info:
  version: 1.0.0
  title: myapp
  description: fullstack-challenge
basePath: /api/v1
tags:
  - name: Professionals
    description: Simple professional endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

definitions:
  ExampleBody:
    type: object
    title: professional
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

paths:
  /:
    get:
      tags:
        - Professionals
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Professionals
      description: Create a new professional
      parameters:
        - name: professional
          in: body
          description: an professional
          required: true
          schema:
            $ref: '#/definitions/ExampleBody'
      responses:
        200:
          description: Returns all examples

  /professional_type:
    get:
      tags:
        - Professional types
      description: Fetch all professional types
      responses:
        200:
          description: Returns all professional types
    post:
      tags:
        - Professionals
      description: Create a new professional
      parameters:
        - name: professional
          in: body
          description: an professional
          required: true
          schema:
            $ref: '#/definitions/ExampleBody'
      responses:
        200:
          description: Returns all examples

  /{id}:
    get:
      tags:
        - Professionals
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the professional to retrieve
          type: integer
      responses:
        200:
          description: Return the professional with the specified id
        404:
          description: Example not found
    put:
      tags:
        - Professionals
      parameters:
        - name: professional
          in: body
          description: an professional
          required: true
          schema:
            $ref: '#/definitions/ExampleBody'
        - name: id
          in: path
          required: true
          description: The id of the professional to retrieve
          type: integer
      responses:
        200:
          description: Return the professional with the specified id
        404:
          description: Example not found
    delete:
      tags:
        - Professionals
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the professional to retrieve
          type: integer
      responses:
        200:
          description: Return the professional with the specified id
        404:
          description: Example not found

  /professional_type/{id}:
    get:
      tags:
        - Professionals type
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the professional to retrieve
          type: integer
      responses:
        200:
          description: Return the professional with the specified id
        404:
          description: Example not found
    put:
      tags:
        - Professionals
      parameters:
        - name: professional
          in: body
          description: an professional
          required: true
          schema:
            $ref: '#/definitions/ExampleBody'
        - name: id
          in: path
          required: true
          description: The id of the professional to retrieve
          type: integer
      responses:
        200:
          description: Return the professional with the specified id
        404:
          description: Example not found
    delete:
      tags:
        - Professionals
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the professional to retrieve
          type: integer
      responses:
        200:
          description: Return the professional with the specified id
        404:
          description: Example not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
